---
- name: Install Apache HTTP Server
  hosts: all
  become: yes

  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present
